-- Permanent application identities and Python lab results.
-- Run after room-code-migration.sql in the hosted Supabase SQL Editor.

create table if not exists public.app_users (
    id bigint generated by default as identity primary key,
    legacy_user_id bigint unique,
    username text unique not null,
    password_hash text,
    full_name text not null,
    role text not null check (role in ('instructor', 'student')),
    seat text,
    location text not null default 'classroom'
        check (location in ('classroom', 'python_lab')),
    device_id text unique,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.game_results (
    id bigint generated by default as identity primary key,
    legacy_result_id bigint unique,
    user_id bigint not null references public.app_users(id) on delete cascade,
    game_name text not null,
    student_name text not null default '',
    score integer not null default 0,
    duration_seconds integer not null default 0,
    correct_answers integer not null default 0,
    wrong_answers integer not null default 0,
    completed_exercises integer not null default 0,
    total_exercises integer not null default 12,
    accuracy numeric(5,2) not null default 0,
    status text not null
        check (status in ('completed', 'instructor_return', 'disconnected')),
    completed_at timestamptz not null default now()
);

create index if not exists game_results_user_id_idx
on public.game_results(user_id);

-- Existing hosted tables may predate the legacy mapping columns above.
alter table public.app_users
add column if not exists legacy_user_id bigint unique;

alter table public.game_results
add column if not exists legacy_result_id bigint unique;

alter table public.game_results
add column if not exists student_name text not null default '',
add column if not exists correct_answers integer not null default 0,
add column if not exists wrong_answers integer not null default 0,
add column if not exists completed_exercises integer not null default 0,
add column if not exists total_exercises integer not null default 12,
add column if not exists accuracy numeric(5,2) not null default 0;

alter table public.participants
add column if not exists user_id bigint
references public.app_users(id)
on delete set null;

create index if not exists participants_user_id_idx
on public.participants(user_id);

create unique index if not exists participants_room_user_idx
on public.participants(room_id, user_id)
where user_id is not null;

alter table public.app_users enable row level security;
alter table public.game_results enable row level security;

-- No browser policies are created. These tables are accessed by the Node server
-- with its server-only secret key; browser clients cannot read or modify them.
