-- Weekly learning content for the VR classroom.
-- Run after 00-base-schema.sql, room-code-migration.sql, and app-data-migration.sql.
-- This migration is additive and safe to rerun.

create table if not exists public.learning_weeks (
    id bigint generated by default as identity primary key,
    week_number integer not null unique check (week_number > 0),
    title text not null,
    description text not null default '',
    is_published boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.week_lessons (
    id bigint generated by default as identity primary key,
    week_id bigint not null references public.learning_weeks(id) on delete cascade,
    lesson_number integer not null check (lesson_number > 0),
    title text not null,
    description text not null default '',
    is_enabled boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (week_id, lesson_number)
);

create table if not exists public.week_activities (
    id bigint generated by default as identity primary key,
    week_id bigint not null references public.learning_weeks(id) on delete cascade,
    lesson_id bigint references public.week_lessons(id) on delete cascade,
    activity_order integer not null check (activity_order > 0),
    activity_type text not null check (activity_type in ('presentation', 'challenge', 'game', 'briefing')),
    title text not null,
    description text not null default '',
    game_key text,
    asset_path text,
    environment_path text,
    duration_seconds integer check (duration_seconds is null or duration_seconds > 0),
    settings jsonb not null default '{}'::jsonb,
    is_enabled boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- Upgrade databases created by the earlier migration version.
alter table public.week_activities
add column if not exists lesson_id bigint references public.week_lessons(id) on delete cascade;

-- Replace the old week-wide ordering constraint with lesson-aware uniqueness.
alter table public.week_activities drop constraint if exists week_activities_week_id_activity_order_key;
create unique index if not exists week_activities_lesson_order_idx
on public.week_activities(lesson_id, activity_order)
where lesson_id is not null;
create unique index if not exists week_activities_week_game_order_idx
on public.week_activities(week_id, activity_order)
where lesson_id is null;
create index if not exists week_lessons_week_id_idx on public.week_lessons(week_id, lesson_number);
create index if not exists week_activities_week_id_idx on public.week_activities(week_id, activity_order);
create index if not exists week_activities_lesson_id_idx on public.week_activities(lesson_id, activity_order);

alter table public.quiz_questions
add column if not exists activity_id bigint references public.week_activities(id) on delete set null;
create index if not exists quiz_questions_activity_id_idx on public.quiz_questions(activity_id);

alter table public.game_results
add column if not exists activity_id bigint references public.week_activities(id) on delete set null;
create index if not exists game_results_activity_id_idx on public.game_results(activity_id);

alter table public.rooms
add column if not exists active_week_id bigint references public.learning_weeks(id) on delete set null;
create index if not exists rooms_active_week_id_idx on public.rooms(active_week_id);

alter table public.learning_weeks enable row level security;
alter table public.week_lessons enable row level security;
alter table public.week_activities enable row level security;

insert into public.learning_weeks (week_number, title, description, is_published)
values
  (1, 'Literal Computers and the Five Computer Parts', 'CPU, RAM, storage, input, output, challenge, game, and debrief.', true),
  (2, 'Variables', 'Variables and data-types learning activities.', false)
on conflict (week_number) do update
set title = excluded.title,
    description = excluded.description;

-- The current instructor UI expects three Week 1 lessons.
insert into public.week_lessons (week_id, lesson_number, title, description)
select w.id, x.lesson_number, x.title, x.description
from public.learning_weeks w
cross join (values
  (1, 'Literal Computers and the Five Computer Parts', 'CPU, RAM, storage, input, and output.'),
  (2, 'Loading and Classification', 'How programs load and how hardware and software are classified.'),
  (3, 'Language Ladder and Translators', 'How source code reaches the CPU through translators.')
) as x(lesson_number, title, description)
where w.week_number = 1
on conflict (week_id, lesson_number) do update
set title = excluded.title,
    description = excluded.description,
    updated_at = now();

-- Lesson 1 presentation/challenge/debrief.
insert into public.week_activities (
  week_id, lesson_id, activity_order, activity_type, title, description,
  game_key, asset_path, environment_path, duration_seconds
)
select w.id, l.id, x.activity_order, x.activity_type, x.title, x.description,
       x.game_key, x.asset_path, x.environment_path, x.duration_seconds
from public.learning_weeks w
join public.week_lessons l on l.week_id = w.id and l.lesson_number = 1
cross join (values
  (1, 'presentation', 'Literal Computers and the Five Computer Parts', 'Present CPU, RAM, storage, input, and output.', null, '/videos/week-1/w1-1-final-video.mp4', null, null),
  (2, 'challenge', 'Five Parts Challenge', 'Identify the job of each computer component.', null, null, './textures/quiz/quick-challenge-space-360.png', 60),
  (3, 'briefing', 'Five Parts Debrief', 'Review the five-part computer model.', null, './images/briefings/week-1/five-parts-of-every-computer-debrief.png', null, null)
) as x(activity_order, activity_type, title, description, game_key, asset_path, environment_path, duration_seconds)
where w.week_number = 1
on conflict (lesson_id, activity_order) where lesson_id is not null do update
set activity_type = excluded.activity_type, title = excluded.title,
    description = excluded.description, game_key = excluded.game_key,
    asset_path = excluded.asset_path, environment_path = excluded.environment_path,
    duration_seconds = excluded.duration_seconds, updated_at = now();

-- Lesson 2 shell; the D2 update file supplies the final wording/question.
insert into public.week_activities (week_id, lesson_id, activity_order, activity_type, title, description, asset_path, environment_path, duration_seconds)
select w.id, l.id, x.activity_order, x.activity_type, x.title, x.description, x.asset_path, x.environment_path, x.duration_seconds
from public.learning_weeks w
join public.week_lessons l on l.week_id = w.id and l.lesson_number = 2
cross join (values
  (1, 'presentation', 'Loading and Classification', 'Present storage, RAM, CPU, hardware, and software.', '/videos/week-1/w1-2-final-video.mp4', null, null),
  (2, 'challenge', 'Loading and Classification Challenge', 'Check how programs load and components are classified.', null, './textures/quiz/quick-challenge-space-360.png', 60),
  (3, 'briefing', 'Loading and Classification Debrief', 'Review program loading, hardware, and software.', '/images/briefings/week-1/loading-and-classification-debrief.png', null, null)
) as x(activity_order, activity_type, title, description, asset_path, environment_path, duration_seconds)
where w.week_number = 1
on conflict (lesson_id, activity_order) where lesson_id is not null do update
set activity_type = excluded.activity_type, title = excluded.title,
    description = excluded.description, asset_path = excluded.asset_path,
    environment_path = excluded.environment_path, duration_seconds = excluded.duration_seconds,
    updated_at = now();

-- Lesson 3 shell; the D3 update file supplies the final wording/question.
insert into public.week_activities (week_id, lesson_id, activity_order, activity_type, title, description, asset_path, environment_path, duration_seconds)
select w.id, l.id, x.activity_order, x.activity_type, x.title, x.description, x.asset_path, x.environment_path, x.duration_seconds
from public.learning_weeks w
join public.week_lessons l on l.week_id = w.id and l.lesson_number = 3
cross join (values
  (1, 'presentation', 'Language Ladder and Translators', 'Explain how source code reaches the CPU.', null, null, null),
  (2, 'challenge', 'Translators Challenge', 'Check compilers, interpreters, and machine language.', null, './textures/quiz/quick-challenge-space-360.png', 60),
  (3, 'briefing', 'Language Ladder and Translators Debrief', 'Review how Python instructions reach the CPU.', '/images/briefings/week-1/language-ladder-and-translators-debrief.png', null, null)
) as x(activity_order, activity_type, title, description, asset_path, environment_path, duration_seconds)
where w.week_number = 1
on conflict (lesson_id, activity_order) where lesson_id is not null do update
set activity_type = excluded.activity_type, title = excluded.title,
    description = excluded.description, asset_path = excluded.asset_path,
    environment_path = excluded.environment_path, duration_seconds = excluded.duration_seconds,
    updated_at = now();

-- One week-level game. It intentionally has no lesson_id.
insert into public.week_activities (
  week_id, lesson_id, activity_order, activity_type, title, description, game_key
)
select w.id, null, 100, 'game', 'Variable Sorting',
       'Sort Python values into the correct data-type bins.', 'python-type-lab'
from public.learning_weeks w
where w.week_number = 1
on conflict (week_id, activity_order) where lesson_id is null do update
set title = excluded.title, description = excluded.description,
    game_key = excluded.game_key, updated_at = now();
